[package]
name = "parsec-interface"
version = "0.4.0"
authors = ["Paul Howard <paul.howard@arm.com>",
           "Ionut Mihalcea <ionut.mihalcea@arm.com>",
           "Hugues de Valon <hugues.devalon@arm.com>"]
edition = "2018"

[build-dependencies]
prost-build = "0.5.0"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.1.4"
num-traits = "0.2"
num-derive = "0.2"
num = "0.2.0"
prost = "0.5.0"
bytes = "0.4.12"
uuid = "0.7.4"

[features]
testing = []
