[package]
name = "parsec-interface"
version = "0.11.0"
authors = ["Paul Howard <paul.howard@arm.com>",
           "Ionut Mihalcea <ionut.mihalcea@arm.com>",
           "Hugues de Valon <hugues.devalon@arm.com>"]
description = "Parsec interface library to communicate using the wire protocol"
license = "Apache-2.0"
repository = "https://github.com/parallaxsecond/parsec-interface-rs"
readme = "README.md"
keywords = ["parsec", "interface", "serialization"]
categories = ["encoding"]
edition = "2018"

[build-dependencies]
prost-build = "0.6.1"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.1.4"
num-traits = "0.2"
num-derive = "0.2"
num = "0.2.0"
prost = "0.6.1"
bytes = "0.4.12"
arbitrary = { version = "0.4.0", features = ["derive"] }
uuid = "0.7.4"
log = "0.4.8"

[features]
testing = []
fuzz = []
